### ISSUE TITLE
Invert appearance of [Default KML script folder] 

### ISSUE THREAD

**Issue by ThomasAH** [dgis/emu48android#5] opened 2019-06-09 07:47 UTC
Emu48 for Android 1.4:

After using the New... menu to create a new calculator instance, the "Pick a calculator" dialog lists 1. the default KML scripts, 2. [Select a Custom KML script folder...] and 3. [Default KML script folder]. The third should not be here.

After selecting a custom folder, the "Pick a calculator" only has 1. the KML files from this folder and 2. [Select a Custom KML script folder...]. The third ([Default KML script folder]) is missing here, so the only way to get back to the default KML script folder is to clear the data of the app.

P.S.: Thank you very much for the Android port of Emu48, and even more (mainly for the 28S) for Emu42!

**Comment by dgis** [comment] 2019-06-10 10:35
Thank you for your report.

For the 1st point, you suggest that the menu entry "[Default KML script folder]" should not be there because we are already showing the default KML scripts, am I right?

For the 2nd point, I'm not able to reproduce your issues because as shown in the 1st point, "[Default KML script folder]" is always there!
If it is missing, could you indicate what is the version of Android (eventually the device model).
And also, could you join a snapshot of your device screen with the missing "[Default KML script folder]", please?

**Comment by ThomasAH** [comment] 2019-06-11 10:49
1st: Yes, if the default KML folder is shown, hiding "[Default KML script folder]" is good to avoid confusion.

2nd: I just noticed that this only happens when selecting a directory that does not contain any KML files, so a workaround for me is to select any directory with KML files (even if they are for Emu42), then the entry "[Default KML script folder]" appears again. I'm using a Fairphone 2 with Android 7 (Fairphone Open 19.x).

**Comment by dgis** [comment] 2019-06-16 13:20
Thank you, I can reproduce 2)!

**Comment by dgis** [comment] 2020-04-10 22:44
Both points are now fixed.

**Closed** 2020-04-10 22:44 UTC
